### ISSUE TITLE
This string is not saved correctly

### ISSUE THREAD

**Issue by tryphe** [anbud/ybin#1]
This line:

`QMap<qint32 /*key*/, qint32 /*value*/> map;`

is saved as:

`QMap<qint32 /*key*/, qint32 /*value*></qint32> map;`

If I put a space between '/' and '<' it saves fine. I guess it's something to do with escape characters. It would be nice to be able to save code without running into that, though. :smiley:

**Comment by Dmitriusan** [comment]
That is mostly a fork of https://github.com/sebsauvage/ZeroBin
So probably it makes sense to ask this question here

**Comment by Dmitriusan** [comment]
@kwentzell ,

looks like the most maintained fork is here https://github.com/elrido/ZeroBin

**Comment by anbud** [comment]
Hello.

First of all, sorry for the late reply.
@Dmitriusan is right, this is a fork of ZeroBin, but I'll look into it in the following days, and fix it accordingly.

**Comment by anbud** [comment]
Fixed and it's live in production. You don't need to resave your paste, it was merely a problem with decryption, the data was saved correctly.
