### ISSUE TITLE
Reading/selecting paste broken for Firefox 53 and Edge

### ISSUE THREAD

**Issue by Herugrim** [anbud/ybin#2]
I noticed that opening a paste on ybin is only working decently with Google Chrome (at least version 58) . If i have a multiline paste, like:

https://ybin.me/p/95ac114b298c7337#SY0WgFX/DYdZU5NUdBX7ANXoVq82T5/jhiOVC887yTc=

I only get about 3 lines (you can scroll down) in Firefox 53 and/or Edge and i cannot select the text. I have spent some time looking at the CSS file but I am not skilled enough to fix it. A height: 500px in .nano-content will show more content but does not fix the selection issue.

**Comment by anbud** [comment]
Hello.
Thank you for the report. It's fixed in production, and I'll push the fixes soon.
